export const USER_ROLES = {
  ADMIN: "ADMIN",
  ADVOCATE: "ADVOCATE",
  JUDGE: "JUDGE",
  CLIENT: "CLIENT",
  STAFF: "STAFF",
};

export const USER_STATUSES = {
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
};

export const CASE_STATUSES = {
  FILED: "FILED",
  UNDER_TRIAL: "UNDER_TRIAL",
  DISMISSED: "DISMISSED",
  DECIDED: "DECIDED",
  CLOSED: "CLOSED",
};

export const HEARING_STATUSES = {
  SCHEDULED: "SCHEDULED",
  COMPLETED: "COMPLETED",
  ADJOURNED: "ADJOURNED",
  CANCELLED: "CANCELLED",
};



